# Generated by Django 5.1.3 on 2026-07-24 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("club_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("abbreviation", models.CharField(blank=True, max_length=3, null=True)),
                ("raw_api_data", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
                ("url", models.URLField(max_length=500)),
                ("cutoff_date", models.DateField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("hidden", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("match_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("url", models.URLField()),
                ("status", models.CharField(max_length=50)),
                ("score_club1", models.FloatField(default=0)),
                ("score_club2", models.FloatField(default=0)),
                ("boards", models.IntegerField(default=0)),
                ("raw_api_data", models.JSONField(blank=True, null=True)),
                (
                    "club1",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matches_home",
                        to="tournoi.club",
                    ),
                ),
                (
                    "club2",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matches_away",
                        to="tournoi.club",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="tournoi.competition",
                    ),
                ),
            ],
        ),
    ]
