# Generated by Django 5.1.3 on 2026-07-24 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournoi", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="club",
            old_name="raw_api_data",
            new_name="raw_data",
        ),
        migrations.RenameField(
            model_name="competition",
            old_name="nom",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="match",
            old_name="boards",
            new_name="num_boards",
        ),
        migrations.RenameField(
            model_name="match",
            old_name="raw_api_data",
            new_name="raw_data",
        ),
        migrations.RenameField(
            model_name="match",
            old_name="score_club1",
            new_name="score_team1",
        ),
        migrations.RenameField(
            model_name="match",
            old_name="score_club2",
            new_name="score_team2",
        ),
        migrations.RemoveField(
            model_name="club",
            name="club_id",
        ),
        migrations.RemoveField(
            model_name="match",
            name="club1",
        ),
        migrations.RemoveField(
            model_name="match",
            name="club2",
        ),
        migrations.RemoveField(
            model_name="match",
            name="match_id",
        ),
        migrations.RemoveField(
            model_name="match",
            name="url",
        ),
        migrations.AddField(
            model_name="match",
            name="team1",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matches_as_team1",
                to="tournoi.club",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="team2",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matches_as_team2",
                to="tournoi.club",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="id",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="club",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="match",
            name="id",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
