# Generated by Django 5.1.3 on 2026-08-05 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournoi", "0002_rename_raw_api_data_club_raw_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="cutoff_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="competition",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
