# Generated by Django 5.1.3 on 2026-08-05 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournoi", "0003_alter_competition_cutoff_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="raw_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
