# Generated by Django 5.1.3 on 2026-08-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournoi", "0004_competition_raw_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="competition",
            options={"ordering": ["-sort_order"]},
        ),
        migrations.AddField(
            model_name="competition",
            name="sort_order",
            field=models.IntegerField(default=0),
        ),
    ]
