# Generated by Django 5.1.3 on 2026-08-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournoi", "0005_alter_competition_options_competition_sort_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="competition",
            options={"ordering": ["-year", "-sort_order", "name"]},
        ),
        migrations.AddField(
            model_name="competition",
            name="year",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="competition",
            name="raw_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
