# Generated by Django 5.1.3 on 2026-08-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournoi", "0006_alter_competition_options_competition_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="status",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="club",
            name="name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="match",
            name="name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="match",
            name="status",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
