# Generated by Django 5.1.3 on 2026-08-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tournoi",
            "0007_competition_status_alter_club_name_alter_match_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="raw_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="match",
            name="raw_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
